query getProduct($ean: String){
  getProductBySpecificationFilter(ean: $ean){
    status
    data {
      productId
      productName
      MultipleEan
      linkText
      items {
        itemId
        nameComplete
      }
    }
  }
}
